Repository SakshiShreya/first-step-pharma-fe, pull requests merged in 2021-12, with the labels that each got.

#28 Issue 24 create services
  src/components/footer/Footer.tsx
  src/components/generic/loader/Loader.module.scss
  src/components/generic/loader/Loader.tsx
  src/components/generic/loader/loader.module.scss
  src/components/homePage/HomePage.module.scss
  src/components/homePage/HomePage.tsx
  src/components/homePage/cover/Cover.module.scss
  src/components/homePage/cover/Cover.tsx
  src/components/homePage/services/Services.module.scss
  src/components/homePage/services/Services.tsx
  src/routes.tsx
  src/types/apiResponses.ts
  src/types/genericTypes.ts
Labels: Home Page, Services

#39 404 page created,issue fixed #32
  src/components/error/Error404.module.scss
  src/components/error/Error404.tsx
  src/routes.tsx
Labels: misc

#40 Emphasize logo
  src/App.scss
  src/App.tsx
  src/assets/images/firstStepLogo.png
  src/assets/images/firstStepLogo1.svg
  src/assets/images/firstStepLogo2.svg
  src/assets/scss/partials/_theme.scss
  src/components/error/Error404.module.scss
  src/components/header/Header.module.scss
  src/components/header/Header.tsx
  src/components/homePage/services/Services.module.scss
Labels: bug

#42 button created and home is linked with name
  src/App.scss
  src/components/error/Error404.module.scss
  src/components/header/Header.module.scss
  src/components/header/Header.tsx
  src/components/homePage/cover/Cover.module.scss
Labels: bug

#43 mobile menu clising issue fixed'
  src/components/header/Header.tsx
Labels: bug
